job_index:
    path:     /
    defaults: { _controller: "JobeetBundle:Job:index" }
    methods:  [GET]

job_show:
    path:  /{id}/{company}/{location}/{position}
    defaults: { _controller: "JobeetBundle:Job:show" }
    methods:  GET
    requirements:
      id: \d+

job_new:
    path:     /new
    defaults: { _controller: "JobeetBundle:Job:new" }
    methods:  [GET, POST]

job_edit:
    path:     /{token}/edit
    defaults: { _controller: "JobeetBundle:Job:edit" }
    methods:  [GET, POST]

job_delete:
    path:     /{token}/delete
    defaults: { _controller: "JobeetBundle:Job:delete" }
    methods:  [POST]

job_preview:
    path:  /{token}/{company}/{location}/{position}
    defaults: { _controller: "JobeetBundle:Job:preview" }
    requirements:
        token: \w+

job_publish:
    path: /{token}/publish
    defaults: { _controller: "JobeetBundle:Job:publish"}
    methods: [POST]
