jobeet_job:
    resource: "@JobeetBundle/Resources/config/routing/job.yml"
    prefix:   /job

jobeet_homepage:
    path:     /hello/{name}
    defaults: { _controller: JobeetBundle:Default:index }


