jobeet_job:
    resource: "@JobeetBundle/Resources/config/routing/job.yml"
    prefix:   /job

jobeet_homepage:
    path:     /
    defaults: {  _controller: JobeetBundle:Job:index }


JobeetBundle_category:
    path:  /category/{slug}
    defaults: { _controller: JobeetBundle:Category:show }